### ISSUE TITLE
Make -g and -x arguments mutually exclusive

### ISSUE THREAD

**Issue by petroav** [prestodb/tempto#117]
While running the presto-product-tests on docker I specified both of these arguments by mistake and the tests started running. I think specifying both doesn't make sense and we should error out if a user does that. The exact command I ran was `presto-product-tests/bin/run_on_docker.sh singlenode -x quarantine,big_query -g hive_connector` and all tests ran.

**Comment by brian-rickman** [comment]
Since one test can be in multiple groups, it might make sense to have both. 

Test_1 is in group_a
Test_2 is in group_a
Test_3 is in group_a and quarantine.

I want to run Test_1 and Test_2 but not Test_3, it would be convenient to say:
-g group_a -x quarantine.

**Comment by petroav** [comment]
That's a good point. However, in the above command, I saw all 301 tests get executed, which to me looks like a bug. I think the expected behavior when both `-g` and `-x` are specified should be exactly as you describe it.

**Comment by brian-rickman** [comment]
I agree that executing all tests when both flags are specified is a bug.

**Comment by kokosing** [comment]
@petroav This is no longer an issue. I have run the same command as you did and only 12 tests were selected.

Test is selected only when:
 - its name matches to `-t` if this option is specified
 - its group matches to `-g` if this option is specified
 - its group does not match to `-x` if this option is specified
