### ISSUE TITLE
Add support for running quarantined tests when specified explicitly using `-t <testname>`

### ISSUE THREAD

**Issue by amrutagokhale** [prestodb/tempto#122]
There should be support for running a single test, which is tagged under `QUARANTINE` group, when specified via `-t <testname>` option. At present, if you try to run such a test explicitly, the test doesn't run. For ex. when I tried running `testInsertIntoValuesToHiveTableAllHiveSimpleTypes`, I expected it to run even though it comes under `QUARANTINE` group, since I was specifying the name of the test explicitly:
`./presto-product-tests/bin/run_on_docker.sh singlenode -t testInsertIntoValuesToHiveTableAllHiveSimpleTypes`

This is the output I got:
```
INFO: 0 SUCCEEDED      /      0 FAILED      /      0 SKIPPED

===============================================
tempto-tests
Total tests run: 0, Failures: 0, Skips: 0
===============================================
```

**Comment by arhimondr** [comment]
It is supported. You just need to specify the entire test name. For your case it will look like `./presto-product-tests/bin/run_on_docker.sh singlenode -t com.facebook.presto.tests.hive.TestInsertIntoHiveTable.testInsertIntoValuesToHiveTableAllHiveSimpleTypes`

**Comment by amrutagokhale** [comment]
Specifying the entire test name doesn't change the result. I also tried specifying a dummy exclusion group via `./presto-product-tests/bin/run_on_docker.sh singlenode -t com.facebook.presto.tests.hive.TestInsertIntoHiveTable.testInsertIntoValuesToHiveTableAllHiveSimpleTypes -x dummy`, but got the same result.

**Comment by kokosing** [comment]
It should be possible now (after https://github.com/prestodb/tempto/commit/9329bfe8f8cc52d266343da874a2c1d2197c6ab4)

Just make sure that test group is not excluded with `-x`.
