### ISSUE TITLE
Add cleanup method registry

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/tempto#123]
There should be a way to register a cleanup methods to be invoked when test method ends (correctly or abnormally).
Rationale: https://github.com/prestodb/presto/pull/4985#discussion_r59222727

Things to consider:
What to do when cleanup method throws?
Possible solutions:
1. should fail whole test suite (because env is not clean and test results of following tests may be not meaningful)
2. log failure on cleanup and continue
3. introduce dependency mechanism to establish dependencies between tests so we can stop only tests depending on the same env

**Comment by maciejgrzybek** [comment]
I personally prefer first or second solution. Third sounds like a big overengineering.
@electrum, @kokosing please comment.

**Comment by kokosing** [comment]
@maciejgrzybek what about using a method annotated with `@AfterMethodWithContext`?

**Comment by maciejgrzybek** [comment]
@kokosing yes, it's sufficient. Thank you for pointing this out!
Here's a PR rewriting the mentioned earlier product test to use `@AfterMethodWithContext` annotation: https://github.com/prestodb/presto/pull/5914.

Closing this ticket since we don't need anything more than just the mentioned annotation.

**Comment by kokosing** [comment]
nice, thanks :)
