### ISSUE TITLE
Rework cleanup mechanism so we do not drop whole schema before tests execution 

### ISSUE THREAD

**Issue by losipiuk** [prestodb/tempto#17]
Idea:
Mark mutable tables with some pattern and drop only those.
For immutable tables drop only when new tests execution requires a table and data have changed.

cc: @kokosing , @sopel39

**Comment by kokosing** [comment]
@losipiuk  I think it is eligible to be closed as tempto no longer removes whole schema. It seems to befixed with https://github.com/prestodb/tempto/commit/6f54faadce49ac8d807111a9089fe05ee89f7e63
