### ISSUE TITLE
Convention tests result files should be optional.

### ISSUE THREAD

**Issue by kokosing** [prestodb/tempto#174]
That way it should be easy to write a convention test as user could write only they query file (*.sql) and execute it to dump result file. Check the result file if it is correct and store it near to the sql file.

Currently tempto fails when it tries to execute the query without result file, saying that no result files exists for test.

I would like to implement this, but I don't know what should be the semantic of absent result file. Either tempto should expect no rows (and throw assertion error if they are any), or should not assert result set (just the query completion).

@brian-rickman @losipiuk 
I would love to hear your opinion about this.

**Comment by brian-rickman** [comment]
I think generating results should require some specific action on the part of the person running the test.  Adding a command line parameter is probably the most user friendly option:

`run_on_docker.sh singlenode -g example_smoketest --generate_results`

I think having Tempto assert when the result set is missing is good, so we won't accidentally check in tests without results.

**Comment by kokosing** [comment]
Ok. Let me put in my words, to check I understand it correctly. No result file means for tempto that no results are expected. In case there are some rows returned for the query in that test then the test will end with the failure.

**Comment by brian-rickman** [comment]
Yes, that is how I would expect it to work.

**Comment by kokosing** [comment]
Sounds good to me.
