### ISSUE TITLE
Unable to start tempto runner when cassandra host is not accessible

### ISSUE THREAD

**Issue by kokosing** [prestodb/tempto#190]
```
1) Error injecting constructor, java.lang.IllegalArgumentException: cassandra
  at com.teradata.tempto.internal.fulfillment.table.cassandra.CassandraTableManager.<init>(CassandraTableManager.java:67)
  at com.teradata.tempto.internal.fulfillment.table.cassandra.CassandraTableManager.class(CassandraTableManager.java:47)
  while locating com.teradata.tempto.internal.fulfillment.table.cassandra.CassandraTableManager
  while locating com.teradata.tempto.fulfillment.table.TableManager annotated with @com.google.inject.name.Named(value=cassandra)
  while locating com.teradata.tempto.fulfillment.table.TableManager annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=26, type=MAPBINDER, keyType=java.lang.String)
  at com.teradata.tempto.internal.fulfillment.table.TableManagerDispatcherModuleProvider$TableManagerModule.configure(TableManagerDisp
atcherModuleProvider.java:100) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedM
odule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.teradata.tempto.interna
l.fulfillment.table.TableManagerDispatcherModuleProvider$TableManagerModule -> com.google.inject.multibindings.MapBinder$RealMapBinder
)
  while locating java.util.Map<java.lang.String, com.teradata.tempto.fulfillment.table.TableManager>
    for parameter 0 at com.teradata.tempto.internal.fulfillment.table.TableManagerDispatcherModuleProvider$TableManagerModule.defaultT
ableManagerDispatcher(TableManagerDispatcherModuleProvider.java:116)
  at com.teradata.tempto.internal.fulfillment.table.TableManagerDispatcherModuleProvider$TableManagerModule.defaultTableManagerDispatcher(TableManagerDispatcherModuleProvider.java:116) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.teradata.tempto.internal.fulfillment.table.TableManagerDispatcherModuleProvider$TableManagerModule)
  while locating com.teradata.tempto.fulfillment.table.TableManagerDispatcher
```

CC: @maciejgrzybek

**Comment by maciejgrzybek** [comment]
It's identical to https://github.com/prestodb/presto/issues/6639, isn't it?
I believe the problem is you don't have `cassandra` in `/etc/hosts` but you use it in your `tempto-configuration`.

I don't see any solution code-wise for it, do you?

**Comment by kokosing** [comment]
But if I don't run any test that is using Cassandra, why do I need to have
Cassandra up and running? In tempto-examples there are different tests,
when I run only one of them then I would like to have only these services
provisioned that are needed for that test.

czw., 17.11.2016, 16:15 użytkownik maciejgrzybek <notifications@github.com>
napisał:

**Comment by maciejgrzybek** [comment]
You don't have to have cassandra up and running. You simply need to have `cassandra` entry in `/etc/hosts` to have hostname resolvable.

And speaking of having all deps running while using only a subset of tests... It's how it works for any other DB in tempto currently.
Even though I don't run psql tests, I do have to have psql configured in `tempto-configuration.yaml`.

**Comment by kokosing** [comment]
No. You don't need to have postgres to run hive tests. It is how I use
tempto when I run tpcds tests, I have only hive up and running. It used to
be broken, but I fixed that some time ago

If it does not work for you, then it is a bug you should post.

pt., 18.11.2016, 16:14 użytkownik maciejgrzybek <notifications@github.com>
napisał:

**Comment by kokosing** [comment]
Fixed with https://github.com/prestodb/tempto/commit/f1a8e4619f18d95946d7046d1de66b10b9b347b4
