### ISSUE TITLE
Make mutable table suffix for Cassandra tables shorter

### ISSUE THREAD

**Issue by cawallin** [prestodb/tempto#212]
The mutable table suffix for Cassandra is currently 44 characters long (``tempto_mut__461c1bf0b44d48ccbea9f6368cb8a9e7``), while the max table length for Cassandra is 48 characters. That leaves just 4 characters to identify any given mutable table. We should make the suffix shorter so we can have meaningful table names.

This came up in https://github.com/prestodb/presto/pull/7451.

**Comment by kokosing** [comment]
Fix: https://github.com/prestodb/tempto/pull/214
