### ISSUE TITLE
Support Materialized View in Cassandra

### ISSUE THREAD

**Issue by ebyhr** [prestodb/tempto#216]
This is enhance, not bug.
tempto cassandra currently supports only table. Creating Materialized View successes but Inserting and Dropping fails.
e.g.) [Insert](https://github.com/prestodb/tempto/blob/5251efb627d5dcf8a864904f6c53ebddff503009/tempto-core/src/main/java/com/teradata/tempto/internal/fulfillment/table/cassandra/CassandraTableManager.java#L95) and [Drop](https://github.com/prestodb/tempto/blob/5251efb627d5dcf8a864904f6c53ebddff503009/tempto-core/src/main/java/com/teradata/tempto/internal/fulfillment/table/cassandra/CassandraTableManager.java#L139)

Cassandra version on tempto docker looks like `2.x`, though...

This came up in [prestodb/presto#7363](https://github.com/prestodb/presto/issues/7363).

**Comment by cawallin** [comment]
@ebyhr as a workaround, try to create a Materialized View manually (see https://github.com/prestodb/presto/blob/master/presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestGrantRevoke.java#L154 for an example, you'll want to do testContext().getDependency(QueryExecutor.class, "cassandra")). Thanks for your work on the Cassandra connector!

**Comment by ebyhr** [comment]
Thanks for the comment @cawallin!
I tried the getDependency code, but it failed. I think cassandra code does not implement `QueryExecutor.class`. Therefore, I used `CassandraQueryExecutor` instead of that.

Should I close this issue?

**Comment by cawallin** [comment]
Glad you figured it out! Yes, I don't think we need to implement every language feature for every Presto connector in tempto, so just creating materialized views manually is fine.

**Comment by ebyhr** [comment]
Thanks a lot :)
