### ISSUE TITLE
add QueryAssert#ignoringOrder() method

### ISSUE THREAD

**Issue by arhimondr** [prestodb/tempto#35]
Invoking this method should lead to ignore order during result rows matching

**Comment by kokosing** [comment]
If you need to check if given result set contains rows in any order you need to use:
com.teradata.tempto.assertions.QueryAssert#contains(com.teradata.tempto.assertions.QueryAssert.Row...)
or
com.teradata.tempto.assertions.QueryAssert#contains(java.util.List<com.teradata.tempto.assertions.QueryAssert.Row>)
